/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package main;

import feeder.Nodes;
import monitoring.NodesMonitoring;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.util.Enumeration;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.AbstractButton;
import javax.swing.ButtonGroup;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;
import trn_volt.Trains;

/**
 *
 * @author RSMXD001
 */
public class MainView extends javax.swing.JFrame {

    private final JFileChooser openFileChooser;
    private File fileFeeder;
    private File fileTRNVOLT;
    private File fileMonitoring;
    FileReader fileReaderFeeder;
    FileReader fileReaderTRNVOLT;
    FileReader fileReaderMonitoring;    
    BufferedReader bufferedReaderFeeder ;
    BufferedReader bufferedReaderTRNVOLT;
    BufferedReader bufferedReaderMonitoring;

    
    /**
     * Creates new form MainView
     */
    public MainView() {
        initComponents();
        jCheckBoxEL0.setVisible(false);
        jCheckBoxEL1.setVisible(false);
        jCheckBoxEL2.setVisible(false);
        jCheckBoxEL3.setVisible(false);
        jCheckBoxEL4.setVisible(false);
        jCheckBoxEL5.setVisible(false);
        jCheckBoxEL6.setVisible(false);
        jCheckBoxEL7.setVisible(false);
        jCheckBoxEL8.setVisible(false);
        jCheckBoxEL9.setVisible(false);
        jCheckBoxEL10.setVisible(false);
        jCheckBoxEL11.setVisible(false);
        jCheckBoxEL1_1.setVisible(false);
        jCheckBoxEL1_2.setVisible(false);    
        jCheckBoxELSheffield.setVisible(false);
        jCheckBoxOther1.setVisible(false);
        jCheckBoxOther2.setVisible(false);
        jCheckBoxOther3.setVisible(false);      
        jCheckBoxOther4.setVisible(false);
        jCheckBoxOther5.setVisible(false);
        jCheckBoxOther6.setVisible(false);           
        jCheckBoxWL1.setVisible(false);
        jCheckBoxWL2.setVisible(false);
        jCheckBoxWL3.setVisible(false);
        jCheckBoxWL4.setVisible(false);
        jCheckBoxWL5.setVisible(false);
        jCheckBoxWL6.setVisible(false);
        openFileChooser = new JFileChooser();
        openFileChooser.setCurrentDirectory(new File("c:\\"));
        openFileChooser.setFileFilter(new FileNameExtensionFilter("TXT files","txt"));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        btnOpenFeeder = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnOpenTRN_VOLT = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        chooseRouteLabel = new javax.swing.JLabel();
        jRadioButtonEL = new javax.swing.JRadioButton();
        jRadioButtonWL = new javax.swing.JRadioButton();
        jRadioButtonCustom = new javax.swing.JRadioButton();
        jCheckBoxEL0 = new javax.swing.JCheckBox();
        jCheckBoxEL1 = new javax.swing.JCheckBox();
        jCheckBoxEL2 = new javax.swing.JCheckBox();
        jCheckBoxEL3 = new javax.swing.JCheckBox();
        jCheckBoxEL4 = new javax.swing.JCheckBox();
        jCheckBoxEL5 = new javax.swing.JCheckBox();
        jCheckBoxEL7 = new javax.swing.JCheckBox();
        jCheckBoxEL8 = new javax.swing.JCheckBox();
        jCheckBoxEL6 = new javax.swing.JCheckBox();
        jCheckBoxEL9 = new javax.swing.JCheckBox();
        jCheckBoxEL10 = new javax.swing.JCheckBox();
        jCheckBoxEL11 = new javax.swing.JCheckBox();
        jCheckBoxEL1_1 = new javax.swing.JCheckBox();
        jCheckBoxEL1_2 = new javax.swing.JCheckBox();
        jCheckBoxELSheffield = new javax.swing.JCheckBox();
        jCheckBoxWL1 = new javax.swing.JCheckBox();
        jCheckBoxWL2 = new javax.swing.JCheckBox();
        jCheckBoxWL3 = new javax.swing.JCheckBox();
        jCheckBoxWL4 = new javax.swing.JCheckBox();
        jCheckBoxWL5 = new javax.swing.JCheckBox();
        jCheckBoxWL6 = new javax.swing.JCheckBox();
        jCheckBoxOther1 = new javax.swing.JCheckBox();
        jCheckBoxOther2 = new javax.swing.JCheckBox();
        jCheckBoxOther3 = new javax.swing.JCheckBox();
        jCheckBoxOther4 = new javax.swing.JCheckBox();
        jCheckBoxOther5 = new javax.swing.JCheckBox();
        jCheckBoxOther6 = new javax.swing.JCheckBox();
        jButtonCalculate = new javax.swing.JButton();
        btnOpenMonitoring = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(769, 500));
        setPreferredSize(new java.awt.Dimension(769, 500));
        setSize(new java.awt.Dimension(769, 500));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnOpenFeeder.setText("Open Feeder.txt file");
        btnOpenFeeder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOpenFeederActionPerformed(evt);
            }
        });
        getContentPane().add(btnOpenFeeder, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 25, 170, 30));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 25, 600, 30));

        btnOpenTRN_VOLT.setText("Open TRN_VOLT.txt file");
        btnOpenTRN_VOLT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOpenTRN_VOLTActionPerformed(evt);
            }
        });
        getContentPane().add(btnOpenTRN_VOLT, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 170, 30));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setToolTipText("");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 90, 600, 30));

        chooseRouteLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        chooseRouteLabel.setText("After selecting TRN_VOLT.txt file, select route and zones");
        getContentPane().add(chooseRouteLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 121, 515, 31));

        buttonGroup1.add(jRadioButtonEL);
        jRadioButtonEL.setText("Eastern Leg");
        jRadioButtonEL.setHideActionText(true);
        jRadioButtonEL.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jRadioButtonEL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonELActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButtonEL, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, 100, -1));

        buttonGroup1.add(jRadioButtonWL);
        jRadioButtonWL.setHideActionText(true);
        jRadioButtonWL.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jRadioButtonWL.setLabel("Western Leg");
        jRadioButtonWL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonWLActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButtonWL, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, 100, -1));

        buttonGroup1.add(jRadioButtonCustom);
        jRadioButtonCustom.setText("Custom");
        jRadioButtonCustom.setHideActionText(true);
        jRadioButtonCustom.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jRadioButtonCustom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonCustomActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButtonCustom, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, 100, -1));

        jCheckBoxEL0.setText("0");
        jCheckBoxEL0.setPreferredSize(new java.awt.Dimension(45, 20));
        getContentPane().add(jCheckBoxEL0, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 160, 45, 23));

        jCheckBoxEL1.setText("1");
        jCheckBoxEL1.setPreferredSize(new java.awt.Dimension(45, 20));
        getContentPane().add(jCheckBoxEL1, new org.netbeans.lib.awtextra.AbsoluteConstraints(185, 160, 45, 23));

        jCheckBoxEL2.setText("2");
        jCheckBoxEL2.setPreferredSize(new java.awt.Dimension(45, 20));
        getContentPane().add(jCheckBoxEL2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 160, 45, 23));

        jCheckBoxEL3.setText("3");
        jCheckBoxEL3.setPreferredSize(new java.awt.Dimension(45, 20));
        getContentPane().add(jCheckBoxEL3, new org.netbeans.lib.awtextra.AbsoluteConstraints(275, 160, 45, 23));

        jCheckBoxEL4.setText("4");
        jCheckBoxEL4.setPreferredSize(new java.awt.Dimension(45, 20));
        getContentPane().add(jCheckBoxEL4, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 160, 45, 23));

        jCheckBoxEL5.setText("5");
        jCheckBoxEL5.setPreferredSize(new java.awt.Dimension(45, 20));
        getContentPane().add(jCheckBoxEL5, new org.netbeans.lib.awtextra.AbsoluteConstraints(365, 160, 45, 23));

        jCheckBoxEL7.setText("7");
        jCheckBoxEL7.setPreferredSize(new java.awt.Dimension(45, 20));
        getContentPane().add(jCheckBoxEL7, new org.netbeans.lib.awtextra.AbsoluteConstraints(185, 182, 45, 23));

        jCheckBoxEL8.setText("8");
        jCheckBoxEL8.setPreferredSize(new java.awt.Dimension(45, 20));
        getContentPane().add(jCheckBoxEL8, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 182, 45, -1));

        jCheckBoxEL6.setText("6");
        jCheckBoxEL6.setPreferredSize(new java.awt.Dimension(45, 20));
        getContentPane().add(jCheckBoxEL6, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 182, 45, 23));

        jCheckBoxEL9.setText("9");
        jCheckBoxEL9.setPreferredSize(new java.awt.Dimension(45, 20));
        getContentPane().add(jCheckBoxEL9, new org.netbeans.lib.awtextra.AbsoluteConstraints(275, 182, 45, 23));

        jCheckBoxEL10.setText("10");
        jCheckBoxEL10.setPreferredSize(new java.awt.Dimension(45, 20));
        getContentPane().add(jCheckBoxEL10, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 182, 45, 23));

        jCheckBoxEL11.setText("11");
        jCheckBoxEL11.setPreferredSize(new java.awt.Dimension(45, 20));
        getContentPane().add(jCheckBoxEL11, new org.netbeans.lib.awtextra.AbsoluteConstraints(365, 182, 45, 23));

        jCheckBoxEL1_1.setText("1_1");
        jCheckBoxEL1_1.setPreferredSize(new java.awt.Dimension(45, 20));
        getContentPane().add(jCheckBoxEL1_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 160, 45, -1));

        jCheckBoxEL1_2.setText("1_2");
        jCheckBoxEL1_2.setPreferredSize(new java.awt.Dimension(45, 20));
        getContentPane().add(jCheckBoxEL1_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 183, 45, -1));

        jCheckBoxELSheffield.setText("Sheffield");
        jCheckBoxELSheffield.setToolTipText("");
        jCheckBoxELSheffield.setPreferredSize(new java.awt.Dimension(45, 20));
        getContentPane().add(jCheckBoxELSheffield, new org.netbeans.lib.awtextra.AbsoluteConstraints(455, 160, 70, -1));

        jCheckBoxWL1.setText("1");
        jCheckBoxWL1.setPreferredSize(new java.awt.Dimension(45, 20));
        getContentPane().add(jCheckBoxWL1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 210, 45, 23));

        jCheckBoxWL2.setText("2");
        jCheckBoxWL2.setPreferredSize(new java.awt.Dimension(45, 20));
        getContentPane().add(jCheckBoxWL2, new org.netbeans.lib.awtextra.AbsoluteConstraints(185, 210, 45, 23));

        jCheckBoxWL3.setText("3");
        jCheckBoxWL3.setPreferredSize(new java.awt.Dimension(45, 20));
        getContentPane().add(jCheckBoxWL3, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 210, 45, 23));

        jCheckBoxWL4.setText("4");
        jCheckBoxWL4.setPreferredSize(new java.awt.Dimension(45, 20));
        getContentPane().add(jCheckBoxWL4, new org.netbeans.lib.awtextra.AbsoluteConstraints(275, 210, 45, 23));

        jCheckBoxWL5.setText("5");
        jCheckBoxWL5.setPreferredSize(new java.awt.Dimension(45, 20));
        getContentPane().add(jCheckBoxWL5, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 210, 45, 23));

        jCheckBoxWL6.setText("6");
        jCheckBoxWL6.setPreferredSize(new java.awt.Dimension(45, 20));
        getContentPane().add(jCheckBoxWL6, new org.netbeans.lib.awtextra.AbsoluteConstraints(365, 210, 45, 23));

        jCheckBoxOther1.setText("1");
        jCheckBoxOther1.setPreferredSize(new java.awt.Dimension(45, 20));
        getContentPane().add(jCheckBoxOther1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 260, 45, 23));

        jCheckBoxOther2.setText("2");
        jCheckBoxOther2.setPreferredSize(new java.awt.Dimension(45, 20));
        getContentPane().add(jCheckBoxOther2, new org.netbeans.lib.awtextra.AbsoluteConstraints(185, 260, 45, 23));

        jCheckBoxOther3.setText("3");
        jCheckBoxOther3.setPreferredSize(new java.awt.Dimension(45, 20));
        getContentPane().add(jCheckBoxOther3, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 260, 45, 23));

        jCheckBoxOther4.setText("4");
        jCheckBoxOther4.setPreferredSize(new java.awt.Dimension(45, 20));
        getContentPane().add(jCheckBoxOther4, new org.netbeans.lib.awtextra.AbsoluteConstraints(275, 260, 45, 23));

        jCheckBoxOther5.setText("5");
        jCheckBoxOther5.setPreferredSize(new java.awt.Dimension(45, 20));
        getContentPane().add(jCheckBoxOther5, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 260, 45, 23));

        jCheckBoxOther6.setText("6");
        jCheckBoxOther6.setPreferredSize(new java.awt.Dimension(45, 20));
        getContentPane().add(jCheckBoxOther6, new org.netbeans.lib.awtextra.AbsoluteConstraints(365, 260, 45, 23));

        jButtonCalculate.setText("Calculate Filter TRNVOLT");
        jButtonCalculate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCalculateActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonCalculate, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, 515, 30));

        btnOpenMonitoring.setText("Open Monitoring.txt file");
        btnOpenMonitoring.setPreferredSize(new java.awt.Dimension(150, 23));
        btnOpenMonitoring.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOpenMonitoringActionPerformed(evt);
            }
        });
        getContentPane().add(btnOpenMonitoring, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 375, 170, 30));

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setToolTipText("");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 375, 600, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnOpenFeederActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOpenFeederActionPerformed

        int returnValue = openFileChooser.showOpenDialog(this);
        if (returnValue==JFileChooser.APPROVE_OPTION){
            
            fileFeeder=openFileChooser.getSelectedFile();
            jLabel1.setText(fileFeeder.getAbsolutePath());
            try {
                fileReaderFeeder=new FileReader(fileFeeder);
                bufferedReaderFeeder = new BufferedReader(fileReaderFeeder);
                Nodes nodes=new Nodes(bufferedReaderFeeder);
                CreateExl.createExcelFEEDER(nodes,fileFeeder.getAbsolutePath());
            } catch (FileNotFoundException ex) {
                Logger.getLogger(MainView.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IOException ex) {
                Logger.getLogger(MainView.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        else {
            jLabel1.setText("No file chosen!");
        }
    }//GEN-LAST:event_btnOpenFeederActionPerformed

    private void btnOpenTRN_VOLTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOpenTRN_VOLTActionPerformed

        int returnValue = openFileChooser.showOpenDialog(this);
        if (returnValue==JFileChooser.APPROVE_OPTION){
            
            fileTRNVOLT=openFileChooser.getSelectedFile();
            jLabel2.setText(fileTRNVOLT.getAbsolutePath());
            try {
                fileReaderTRNVOLT=new FileReader(fileTRNVOLT);
                bufferedReaderTRNVOLT = new BufferedReader(fileReaderTRNVOLT);
                Trains trains=new Trains(bufferedReaderTRNVOLT);
                CreateExl.createExcelTRNVOLT(trains,fileTRNVOLT.getAbsolutePath());
            } catch (FileNotFoundException ex) {
                Logger.getLogger(MainView.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IOException ex) {
                Logger.getLogger(MainView.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        else {
            jLabel2.setText("No file chosen!");
        }                                                
    }//GEN-LAST:event_btnOpenTRN_VOLTActionPerformed

    private void jButtonCalculateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCalculateActionPerformed
        // TODO add your handling code here:
        String routeName=getSelectedButtonText(buttonGroup1);
        switch (routeName) {
            case "Eastern Leg": {
                try {
                    if (jCheckBoxEL0.isSelected()) {
                        fileReaderFeeder=new FileReader(fileTRNVOLT);
                        bufferedReaderTRNVOLT = new BufferedReader(fileReaderFeeder);
                        Trains trains0=new Trains(bufferedReaderTRNVOLT,routeName,"0");
                        CreateExl.fillExcelTRNVOLT(trains0,fileTRNVOLT.getAbsolutePath(),"0");
                    }
                    if (jCheckBoxEL1.isSelected()) {
                        fileReaderFeeder=new FileReader(fileTRNVOLT);
                        bufferedReaderTRNVOLT = new BufferedReader(fileReaderFeeder);
                        Trains trains1=new Trains(bufferedReaderTRNVOLT,routeName,"1");
                        CreateExl.fillExcelTRNVOLT(trains1,fileTRNVOLT.getAbsolutePath(),"1");
                    }
                    if (jCheckBoxEL2.isSelected()) {
                        fileReaderFeeder=new FileReader(fileTRNVOLT);
                        bufferedReaderTRNVOLT = new BufferedReader(fileReaderFeeder);
                        Trains trains2=new Trains(bufferedReaderTRNVOLT,routeName,"2");
                        CreateExl.fillExcelTRNVOLT(trains2,fileTRNVOLT.getAbsolutePath(),"2");
                    }
                    if (jCheckBoxEL3.isSelected()) {
                        fileReaderFeeder=new FileReader(fileTRNVOLT);
                        bufferedReaderTRNVOLT = new BufferedReader(fileReaderFeeder);
                        Trains trains3=new Trains(bufferedReaderTRNVOLT,routeName,"3");
                        CreateExl.fillExcelTRNVOLT(trains3,fileTRNVOLT.getAbsolutePath(),"3");
                    }                    
                    if (jCheckBoxEL4.isSelected()) {
                        fileReaderFeeder=new FileReader(fileTRNVOLT);
                        bufferedReaderTRNVOLT = new BufferedReader(fileReaderFeeder);
                        Trains trains4=new Trains(bufferedReaderTRNVOLT,routeName,"4");
                        CreateExl.fillExcelTRNVOLT(trains4,fileTRNVOLT.getAbsolutePath(),"4");
                    }
                    if (jCheckBoxEL5.isSelected()) {
                        fileReaderFeeder=new FileReader(fileTRNVOLT);
                        bufferedReaderTRNVOLT = new BufferedReader(fileReaderFeeder);
                        Trains trains5=new Trains(bufferedReaderTRNVOLT,routeName,"5");
                        CreateExl.fillExcelTRNVOLT(trains5,fileTRNVOLT.getAbsolutePath(),"5");
                    }                   
                    if (jCheckBoxEL6.isSelected()) {
                        fileReaderFeeder=new FileReader(fileTRNVOLT);
                        bufferedReaderTRNVOLT = new BufferedReader(fileReaderFeeder);
                        Trains trains6=new Trains(bufferedReaderTRNVOLT,routeName,"6");
                        CreateExl.fillExcelTRNVOLT(trains6,fileTRNVOLT.getAbsolutePath(),"6");
                    }
                    if (jCheckBoxEL7.isSelected()) {
                        fileReaderFeeder=new FileReader(fileTRNVOLT);
                        bufferedReaderTRNVOLT = new BufferedReader(fileReaderFeeder);
                        Trains trains7=new Trains(bufferedReaderTRNVOLT,routeName,"7");
                        CreateExl.fillExcelTRNVOLT(trains7,fileTRNVOLT.getAbsolutePath(),"7");
                    }
                    if (jCheckBoxEL8.isSelected()) {
                        fileReaderFeeder=new FileReader(fileTRNVOLT);
                        bufferedReaderTRNVOLT = new BufferedReader(fileReaderFeeder);
                        Trains trains8=new Trains(bufferedReaderTRNVOLT,routeName,"8");
                        CreateExl.fillExcelTRNVOLT(trains8,fileTRNVOLT.getAbsolutePath(),"8");
                    }
                    if (jCheckBoxEL9.isSelected()) {
                        fileReaderFeeder=new FileReader(fileTRNVOLT);
                        bufferedReaderTRNVOLT = new BufferedReader(fileReaderFeeder);
                        Trains trains9=new Trains(bufferedReaderTRNVOLT,routeName,"9");
                        CreateExl.fillExcelTRNVOLT(trains9,fileTRNVOLT.getAbsolutePath(),"9");
                    }                  
                    if (jCheckBoxEL10.isSelected()) {
                        fileReaderFeeder=new FileReader(fileTRNVOLT);
                        bufferedReaderTRNVOLT = new BufferedReader(fileReaderFeeder);
                        Trains trains10=new Trains(bufferedReaderTRNVOLT,routeName,"10");
                        CreateExl.fillExcelTRNVOLT(trains10,fileTRNVOLT.getAbsolutePath(),"10");
                    }             
                    if (jCheckBoxEL11.isSelected()) {
                        fileReaderFeeder=new FileReader(fileTRNVOLT);
                        bufferedReaderTRNVOLT = new BufferedReader(fileReaderFeeder);
                        Trains trains11=new Trains(bufferedReaderTRNVOLT,routeName,"11");
                        CreateExl.fillExcelTRNVOLT(trains11,fileTRNVOLT.getAbsolutePath(),"11");
                    }
                    if (jCheckBoxEL1_1.isSelected()) {
                        fileReaderFeeder=new FileReader(fileTRNVOLT);
                        bufferedReaderTRNVOLT = new BufferedReader(fileReaderFeeder);
                        Trains trains1_1=new Trains(bufferedReaderTRNVOLT,routeName,"1_1");
                        CreateExl.fillExcelTRNVOLT(trains1_1,fileTRNVOLT.getAbsolutePath(),"1_1");
                    }
                    if (jCheckBoxEL1_2.isSelected()) {
                        fileReaderFeeder=new FileReader(fileTRNVOLT);
                        bufferedReaderTRNVOLT = new BufferedReader(fileReaderFeeder);
                        Trains trains1_2=new Trains(bufferedReaderTRNVOLT,routeName,"1_2");
                        CreateExl.fillExcelTRNVOLT(trains1_2,fileTRNVOLT.getAbsolutePath(),"1_2");
                    }
                    if (jCheckBoxELSheffield.isSelected()) {
                        fileReaderFeeder=new FileReader(fileTRNVOLT);
                        bufferedReaderTRNVOLT = new BufferedReader(fileReaderFeeder);
                        Trains trainsSheffield=new Trains(bufferedReaderTRNVOLT,routeName,"Sheffield");
                        CreateExl.fillExcelTRNVOLT(trainsSheffield,fileTRNVOLT.getAbsolutePath(),"Sheffield");
                    }
                    
                } catch (IOException ex) {
                    Logger.getLogger(MainView.class.getName()).log(Level.SEVERE, null, ex);
                }
                break;}
            case "Custom":
                try {
                    if (jCheckBoxOther1.isSelected()) {
                        fileReaderFeeder=new FileReader(fileTRNVOLT);
                        bufferedReaderTRNVOLT = new BufferedReader(fileReaderFeeder);
                        Trains trainsCustom=new Trains(bufferedReaderTRNVOLT,routeName,"1");
                        CreateExl.fillExcelTRNVOLT(trainsCustom,fileTRNVOLT.getAbsolutePath(),"1");
                    }      
                    if (jCheckBoxOther2.isSelected()) {
                        fileReaderFeeder=new FileReader(fileTRNVOLT);
                        bufferedReaderTRNVOLT = new BufferedReader(fileReaderFeeder);
                        Trains trainsCustom=new Trains(bufferedReaderTRNVOLT,routeName,"2");
                        CreateExl.fillExcelTRNVOLT(trainsCustom,fileTRNVOLT.getAbsolutePath(),"2");
                    }   
                    if (jCheckBoxOther3.isSelected()) {
                        fileReaderFeeder=new FileReader(fileTRNVOLT);
                        bufferedReaderTRNVOLT = new BufferedReader(fileReaderFeeder);
                        Trains trainsCustom=new Trains(bufferedReaderTRNVOLT,routeName,"3");
                        CreateExl.fillExcelTRNVOLT(trainsCustom,fileTRNVOLT.getAbsolutePath(),"3");
                    } 
                    if (jCheckBoxOther4.isSelected()) {
                        fileReaderFeeder=new FileReader(fileTRNVOLT);
                        bufferedReaderTRNVOLT = new BufferedReader(fileReaderFeeder);
                        Trains trainsCustom=new Trains(bufferedReaderTRNVOLT,routeName,"4");
                        CreateExl.fillExcelTRNVOLT(trainsCustom,fileTRNVOLT.getAbsolutePath(),"4");
                    }      
                    if (jCheckBoxOther5.isSelected()) {
                        fileReaderFeeder=new FileReader(fileTRNVOLT);
                        bufferedReaderTRNVOLT = new BufferedReader(fileReaderFeeder);
                        Trains trainsCustom=new Trains(bufferedReaderTRNVOLT,routeName,"5");
                        CreateExl.fillExcelTRNVOLT(trainsCustom,fileTRNVOLT.getAbsolutePath(),"5");
                    }   
                    if (jCheckBoxOther6.isSelected()) {
                        fileReaderFeeder=new FileReader(fileTRNVOLT);
                        bufferedReaderTRNVOLT = new BufferedReader(fileReaderFeeder);
                        Trains trainsCustom=new Trains(bufferedReaderTRNVOLT,routeName,"6");
                        CreateExl.fillExcelTRNVOLT(trainsCustom,fileTRNVOLT.getAbsolutePath(),"6");
                    }                           
                } catch (IOException ex) {
                    Logger.getLogger(MainView.class.getName()).log(Level.SEVERE, null, ex);
                }                    
            case "Western Leg": 
                try {
                    if (jCheckBoxWL1.isSelected()) {
                        fileReaderFeeder=new FileReader(fileTRNVOLT);
                        bufferedReaderTRNVOLT = new BufferedReader(fileReaderFeeder);
                        Trains trains1=new Trains(bufferedReaderTRNVOLT,routeName,"1");
                        CreateExl.fillExcelTRNVOLT(trains1,fileTRNVOLT.getAbsolutePath(),"1");
                    }
                    if (jCheckBoxWL2.isSelected()) {
                        fileReaderFeeder=new FileReader(fileTRNVOLT);
                        bufferedReaderTRNVOLT = new BufferedReader(fileReaderFeeder);
                        Trains trains2=new Trains(bufferedReaderTRNVOLT,routeName,"2");
                        CreateExl.fillExcelTRNVOLT(trains2,fileTRNVOLT.getAbsolutePath(),"2");
                    }
                    if (jCheckBoxWL3.isSelected()) {
                        fileReaderFeeder=new FileReader(fileTRNVOLT);
                        bufferedReaderTRNVOLT = new BufferedReader(fileReaderFeeder);
                        Trains trains3=new Trains(bufferedReaderTRNVOLT,routeName,"3");
                        CreateExl.fillExcelTRNVOLT(trains3,fileTRNVOLT.getAbsolutePath(),"3");
                    }
                    if (jCheckBoxWL4.isSelected()) {
                        fileReaderFeeder=new FileReader(fileTRNVOLT);
                        bufferedReaderTRNVOLT = new BufferedReader(fileReaderFeeder);
                        Trains trains4=new Trains(bufferedReaderTRNVOLT,routeName,"4");
                        CreateExl.fillExcelTRNVOLT(trains4,fileTRNVOLT.getAbsolutePath(),"4");
                    }                    
                    if (jCheckBoxWL5.isSelected()) {
                        fileReaderFeeder=new FileReader(fileTRNVOLT);
                        bufferedReaderTRNVOLT = new BufferedReader(fileReaderFeeder);
                        Trains trains5=new Trains(bufferedReaderTRNVOLT,routeName,"5");
                        CreateExl.fillExcelTRNVOLT(trains5,fileTRNVOLT.getAbsolutePath(),"5");
                    }
                    if (jCheckBoxWL6.isSelected()) {
                        fileReaderFeeder=new FileReader(fileTRNVOLT);
                        bufferedReaderTRNVOLT = new BufferedReader(fileReaderFeeder);
                        Trains trains6=new Trains(bufferedReaderTRNVOLT,routeName,"6");
                        CreateExl.fillExcelTRNVOLT(trains6,fileTRNVOLT.getAbsolutePath(),"6");
                    } 
                    
                } catch (IOException ex) {
                    Logger.getLogger(MainView.class.getName()).log(Level.SEVERE, null, ex);
                }
            default: System.out.println("Select route!");
        }
    }//GEN-LAST:event_jButtonCalculateActionPerformed

    private void jRadioButtonELActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonELActionPerformed
        // TODO add your handling code here:
        jCheckBoxEL0.setVisible(true);
        jCheckBoxEL1.setVisible(true);
        jCheckBoxEL2.setVisible(true);
        jCheckBoxEL3.setVisible(true);
        jCheckBoxEL4.setVisible(true);
        jCheckBoxEL5.setVisible(true);
        jCheckBoxEL6.setVisible(true);
        jCheckBoxEL7.setVisible(true);
        jCheckBoxEL8.setVisible(true);
        jCheckBoxEL9.setVisible(true);
        jCheckBoxEL10.setVisible(true);
        jCheckBoxEL11.setVisible(true);
        jCheckBoxEL1_1.setVisible(true);
        jCheckBoxEL1_2.setVisible(true);
        jCheckBoxELSheffield.setVisible(true);
        jCheckBoxOther1.setVisible(false);
        jCheckBoxOther2.setVisible(false);
        jCheckBoxOther3.setVisible(false); 
        jCheckBoxOther4.setVisible(false);
        jCheckBoxOther5.setVisible(false);
        jCheckBoxOther6.setVisible(false);         
        jCheckBoxWL1.setVisible(false);
        jCheckBoxWL2.setVisible(false);
        jCheckBoxWL3.setVisible(false);
        jCheckBoxWL4.setVisible(false);
        jCheckBoxWL5.setVisible(false);
        jCheckBoxWL6.setVisible(false);
    }//GEN-LAST:event_jRadioButtonELActionPerformed

    private void jRadioButtonCustomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonCustomActionPerformed
        // TODO add your handling code here:
        jCheckBoxEL0.setVisible(false);
        jCheckBoxEL1.setVisible(false);
        jCheckBoxEL2.setVisible(false);
        jCheckBoxEL3.setVisible(false);
        jCheckBoxEL4.setVisible(false);
        jCheckBoxEL5.setVisible(false);
        jCheckBoxEL6.setVisible(false);
        jCheckBoxEL7.setVisible(false);
        jCheckBoxEL8.setVisible(false);
        jCheckBoxEL9.setVisible(false);
        jCheckBoxEL10.setVisible(false);
        jCheckBoxEL11.setVisible(false);
        jCheckBoxEL1_1.setVisible(false);
        jCheckBoxEL1_2.setVisible(false);
        jCheckBoxELSheffield.setVisible(false);
        jCheckBoxOther1.setVisible(true);
        jCheckBoxOther2.setVisible(true);
        jCheckBoxOther3.setVisible(true);
        jCheckBoxOther4.setVisible(true);
        jCheckBoxOther5.setVisible(true);
        jCheckBoxOther6.setVisible(true);        
        jCheckBoxWL1.setVisible(false);
        jCheckBoxWL2.setVisible(false);
        jCheckBoxWL3.setVisible(false);
        jCheckBoxWL4.setVisible(false);
        jCheckBoxWL5.setVisible(false);
        jCheckBoxWL6.setVisible(false);
    }//GEN-LAST:event_jRadioButtonCustomActionPerformed

    private void jRadioButtonWLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonWLActionPerformed
        // TODO add your handling code here:
        jCheckBoxEL0.setVisible(false);
        jCheckBoxEL1.setVisible(false);
        jCheckBoxEL2.setVisible(false);
        jCheckBoxEL3.setVisible(false);
        jCheckBoxEL4.setVisible(false);
        jCheckBoxEL5.setVisible(false);
        jCheckBoxEL6.setVisible(false);
        jCheckBoxEL7.setVisible(false);
        jCheckBoxEL8.setVisible(false);
        jCheckBoxEL9.setVisible(false);
        jCheckBoxEL10.setVisible(false);
        jCheckBoxEL11.setVisible(false);
        jCheckBoxEL1_1.setVisible(false);
        jCheckBoxEL1_2.setVisible(false);        
        jCheckBoxELSheffield.setVisible(false); 
        jCheckBoxOther1.setVisible(false);
        jCheckBoxOther2.setVisible(false);
        jCheckBoxOther3.setVisible(false);
        jCheckBoxOther4.setVisible(false);
        jCheckBoxOther5.setVisible(false);
        jCheckBoxOther6.setVisible(false);        
        jCheckBoxWL1.setVisible(true);
        jCheckBoxWL2.setVisible(true);
        jCheckBoxWL3.setVisible(true);
        jCheckBoxWL4.setVisible(true);
        jCheckBoxWL5.setVisible(true);
        jCheckBoxWL6.setVisible(true);
    }//GEN-LAST:event_jRadioButtonWLActionPerformed

    private void btnOpenMonitoringActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOpenMonitoringActionPerformed
        // TODO add your handling code here:
        int returnValue = openFileChooser.showOpenDialog(this);
        if (returnValue==JFileChooser.APPROVE_OPTION){
            
            fileMonitoring=openFileChooser.getSelectedFile();
            jLabel3.setText(fileMonitoring.getAbsolutePath());
            System.out.println(fileMonitoring.getAbsolutePath());
            try {
                fileReaderMonitoring=new FileReader(fileMonitoring);
                bufferedReaderMonitoring = new BufferedReader(fileReaderMonitoring);
                NodesMonitoring nodes=new NodesMonitoring(bufferedReaderMonitoring);
                CreateExl.createExcelMonitoring(nodes,fileMonitoring.getAbsolutePath());
            } catch (FileNotFoundException ex) {
                Logger.getLogger(MainView.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IOException ex) {
                Logger.getLogger(MainView.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        else {
            jLabel3.setText("No file chosen!");
        }
        
    }//GEN-LAST:event_btnOpenMonitoringActionPerformed
  
    public String getSelectedButtonText(ButtonGroup buttonGroup) {
        for (Enumeration<AbstractButton> buttons = buttonGroup.getElements(); buttons.hasMoreElements();) {
            AbstractButton button = buttons.nextElement();
            if (button.isSelected()) {
                return button.getText();
            }
        }
        return null;
    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainView().setVisible(true); 
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnOpenFeeder;
    private javax.swing.JButton btnOpenMonitoring;
    private javax.swing.JButton btnOpenTRN_VOLT;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel chooseRouteLabel;
    private javax.swing.JButton jButtonCalculate;
    private javax.swing.JCheckBox jCheckBoxEL0;
    private javax.swing.JCheckBox jCheckBoxEL1;
    private javax.swing.JCheckBox jCheckBoxEL10;
    private javax.swing.JCheckBox jCheckBoxEL11;
    private javax.swing.JCheckBox jCheckBoxEL1_1;
    private javax.swing.JCheckBox jCheckBoxEL1_2;
    private javax.swing.JCheckBox jCheckBoxEL2;
    private javax.swing.JCheckBox jCheckBoxEL3;
    private javax.swing.JCheckBox jCheckBoxEL4;
    private javax.swing.JCheckBox jCheckBoxEL5;
    private javax.swing.JCheckBox jCheckBoxEL6;
    private javax.swing.JCheckBox jCheckBoxEL7;
    private javax.swing.JCheckBox jCheckBoxEL8;
    private javax.swing.JCheckBox jCheckBoxEL9;
    private javax.swing.JCheckBox jCheckBoxELSheffield;
    private javax.swing.JCheckBox jCheckBoxOther1;
    private javax.swing.JCheckBox jCheckBoxOther2;
    private javax.swing.JCheckBox jCheckBoxOther3;
    private javax.swing.JCheckBox jCheckBoxOther4;
    private javax.swing.JCheckBox jCheckBoxOther5;
    private javax.swing.JCheckBox jCheckBoxOther6;
    private javax.swing.JCheckBox jCheckBoxWL1;
    private javax.swing.JCheckBox jCheckBoxWL2;
    private javax.swing.JCheckBox jCheckBoxWL3;
    private javax.swing.JCheckBox jCheckBoxWL4;
    private javax.swing.JCheckBox jCheckBoxWL5;
    private javax.swing.JCheckBox jCheckBoxWL6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JRadioButton jRadioButtonCustom;
    private javax.swing.JRadioButton jRadioButtonEL;
    private javax.swing.JRadioButton jRadioButtonWL;
    // End of variables declaration//GEN-END:variables
}
